version: '3'

services:
  poc:
    build: .
    environment:
      - env_file=.env
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    image: sinapsis-poc/gperez
    container_name: sinapsis-poc-gperez
    command: tail -f /dev/null
    volumes:
      - ./src:/app/src
      - ./coverage:/app/coverage